// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	CustomerName string `json:"customer_name"`
	ProductName  string `json:"product_name"`
	Quantity     int32  `json:"quantity"`
}

type Order struct {
	ID           string `json:"id"`
	CustomerName string `json:"customer_name"`
	ProductName  string `json:"product_name"`
	Quantity     int32  `json:"quantity"`
	CreatedAt    string `json:"createdAt"`
}

type Query struct {
}
